# Generated by Django 2.2.7 on 2019-11-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('cooperation', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
