# Generated by Django 2.2.10 on 2020-04-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='corporation',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
