# Generated by Django 2.2.10 on 2020-04-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyApi', '0002_auto_20200417_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='is_big_ten',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='corporation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_big_ten',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
