# Generated by Django 2.2.10 on 2020-04-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyApi', '0003_auto_20200417_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
