# Generated by Django 2.2.10 on 2020-04-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyApi', '0004_auto_20200417_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downvote_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='upvote_counter',
            field=models.IntegerField(default=0),
        ),
    ]
