# Generated by Django 2.2.10 on 2020-04-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyApi', '0005_auto_20200417_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='blacklist',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
