# Generated by Django 3.0.1 on 2020-04-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyApi', '0006_auto_20200424_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cooperation',
            new_name='corporation',
        ),
    ]
