# Generated by Django 2.2.10 on 2020-04-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyApi', '0007_auto_20200427_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='corporation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
